Repository hmcts/nfdiv-case-api, pull requests merged in 2022-06, with the labels that each got.

#1985 Add owasp suppression
  config/owasp/suppressions.xml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1985

#1934 NFDIV-2274 - Update NoP document to get latest changes
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1934

#1986 Revert "NFDIV-2274 - Update NoP document to get latest changes"
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1986

#1951 NFDIV-1442: Update content for new version of certificate of entitlement
  src/integrationTest/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearingIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/CertificateOfEntitlementContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1951

#1989 Add Welsh partner content function
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1989

#1987 NFDIV-2274 - use new v5 version of NoP sole respondent document.
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1987

#1968 Treat Great Britain as non overseas address
  src/main/java/uk/gov/hmcts/divorce/divorcecase/util/AddressUtil.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicantTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1968

#1974 Nfdiv 2342 add system update role access rights general application
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/SolicitorAndSystemUpdateAccess.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/SolicitorAndSystemUpdateAccessTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1974

#2008 Add missing config for welsh
  src/integrationTest/resources/application.yaml
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2008

#2011 Add common content methods for Welsh partner content
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2011

#2004 Nfdiv-2358 Add events for withdrawn and rejected
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddNote.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmail.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralLetter.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRefund.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadAmendedApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadConfidentialDocument.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocument.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2004

#2000 NFDIV-2025 : Welsh notification to App1 in Joint case when App2 responds with denied HWF
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2000

#2023 Added CVE suppression for spring security 1.0.10 as latest version still has the CVE
  config/owasp/suppressions.xml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2023

#1982 NFDIV-1378 : CO pronouncement list doc updated
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/PronouncementListDocServiceIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1982

#2029 NFDIV-2366: Add AosOverdue as a valid pre-state for Submit AoS event
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2029

#1912 NFDIV-1977 - Add welsh notification for What you need to do template
  src/functionalTest/java/uk/gov/hmcts/divorce/citizen/CitizenSubmitApplicationFT.java
  src/functionalTest/resources/request/casedata/ccd-callback-casedata-joint-application-welsh-email-notification.json
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPaymentIT.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationOutstandingActionNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationOutstandingActionNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1912

#1992 NFDIV-2012 Notification to app1 when switching from joint to sole - welsh
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchToSoleApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleIT.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2SwitchToSoleNotification.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1992

#2006 NFDIV-2023 - Welsh notification for applicant2 when applicant2 approves application.
  src/integrationTest/java/uk/gov/hmcts/divorce/common/Applicant2ApproveIT.java
  src/integrationTest/resources/wiremock/responses/about-to-submit-applicant-2-approved-welsh-notifications.json
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2006

#2027 NFDIV-2021 Joint app1 welsh notification when app1 made changes
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/Applicant1ResubmitIT.java
  src/integrationTest/resources/wiremock/responses/applicant-1-resubmit-application-notification-in-welsh.json
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2027

#2001 Added welsh translation for successful general application
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2001

#1998 NFDIV-2024 : welsh notification changes
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationApprovedReminderTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1998

#1959 nfdiv-2329: bump ccd-config-generator to v3.0.3
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocumentsFT.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAttachScannedDocuments.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1959

#2033 NFDIV-2366: Add AosOverdue to allowed states for app2 update event
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2033

#2002 Added welsh notification for aos disputed
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2002

#2009 Added welsh translation for unsuccessful bailiff application
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/BailiffServiceUnsuccessfulNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2009

#1967 Allow applicant 1 and applicant 2 solicitor to draft conditional order when other applicant solicitor has submitted CO
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrder.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1967

#1915 NFDIV-1975 Application Submitted notification - Welsh template
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1915

#2037 NFDIV-2366: Revert additional states changes
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2037

#1999 Add not disputed applicant1 Welsh email translation
  src/functionalTest/java/uk/gov/hmcts/divorce/common/SubmitAosFT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SoleApplicationNotDisputedNotificationIT.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1999

#2016 NFDIV-2292: Add Welsh App1 Solicitor Email translation
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2016

#2018 NFDIV-2291 : welsh notification
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedOverseasNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2018

#1988 NFDIV-2009
  src/functionalTest/java/uk/gov/hmcts/divorce/common/InviteApplicant2FT.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1988

#2015 NFDIV-2019: Add Welsh template for App1 needs to make changes email
  src/integrationTest/java/uk/gov/hmcts/divorce/common/Applicant2RequestChangesNotificationIT.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2015

#1977 NFDIV-1976
  src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationFT.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1977

#2034 Added welsh translation for joint application when app1 makes changes
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2034

#2026 NFDIV-1987: Set up Welsh email for service application rejected
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerMakeBailiffDecisionIT.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2026

#2005 NFDIV-1983 : welsh notification changes - AOS reminder
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/AosReminderNotificationsTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2005

#2039 NFDIV-2260: Set up Welsh version of Deemed or Dispensed Document
  src/integrationTest/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContentIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeServiceDecisionIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContent.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2039

#1983 NFDIV-1997: Add not disputed app2/respondent Welsh email translation
  src/functionalTest/java/uk/gov/hmcts/divorce/common/SubmitAosFT.java
  src/functionalTest/resources/request/casedata/ccd-callback-casedata-solicitor-submit-aos.json
  src/functionalTest/resources/responses/response-solicitor-submit-aos.json
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationNotDisputedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1983

#2038 NFDIV-2264: Bailiff Approved Document Welsh Translation
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerMakeBailiffDecisionIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/BailiffApprovedOrderContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/BailiffApprovedOrderContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2038

#2032 NFDIV-2266
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2032

#1997 Welsh notification for respondent need to respond
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java
  src/integrationTest/resources/caseworker-reissue-application-about-to-submit-app2-not-sol-rep-reissue-case-welsh-response.json
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1997

#1975 NFDIV-1298 : Conditional Order Granted doc generation
  src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseFT.java
  src/functionalTest/resources/application.yaml
  src/functionalTest/resources/responses/response-system-pronounce-case-joint.json
  src/functionalTest/resources/responses/response-system-pronounce-case.json
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCase.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedDocument.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateConditionalOrderPronouncedDocumentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1975

#2047 NFDIV-2366
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerConfirmServicePaymentIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
  src/main/java/uk/gov/hmcts/divorce/common/event/UpdateAos.java
  src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolStatementOfTruth.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosState.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SetSubmitAosStateTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2047

#1969 NFDIV-2011
  src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemAlertApplicationNotReviewedFT.java
  src/functionalTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemRemindApplicant2FT.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationRemindApplicant2Notification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationNotReviewedNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationRemindApplicant2NotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationNotReviewedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1969

#2042 Bailiff not approved document welsh translation
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerMakeBailiffDecisionIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/BailiffNotApprovedOrderContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/BailiffNotApprovedOrderContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2042

#1995 Nfdiv-2353 Unlink applicant from draft case event
  build.gradle
  charts/nfdiv-case-api/values.preview.template.yaml
  src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUnlinkApplicantFromCaseIT.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateCaseStateAat.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUnlinkApplicantFromCase.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSoleTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUnlinkApplicantFromCaseTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1995

#2070 Use latest front end image instead of PR image which is used for testing
  charts/nfdiv-case-api/values.preview.template.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2070

#2069 NFDIV-2418
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitAos.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2069

#2044 NFDIV-2388
  src/main/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2044

#2058 NFDIV-1991: Configure CO refused Welsh notification and set up tests
  src/functionalTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeDecisionFT.java
  src/functionalTest/resources/request/casedata/ccd-callback-casedata-legal-advisor-make-decision-joint-welsh.json
  src/integrationTest/java/uk/gov/hmcts/divorce/legaladvisor/LegalAdvisorMakeDecisionIT.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2058

#2066 Welsh notification for citizen apply for conditional order
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderReminderNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPendingReminderNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2066

#1805 Remove app1 1 transformation to prevent email notifications and set offline flag for app2 for paper cases
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerReIssueApplicationIT.java
  src/integrationTest/resources/d8-transformation-success-response.json
  src/integrationTest/resources/d8s-transformation-success-response.json
  src/integrationTest/resources/transformation-success-warning-response.json
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/Applicant1Transformer.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1805

#1994 Fix legal advisor state access for all ending states for make decision event
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/LegalAdvisorAccess.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/LegalAdvisorAccessTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-1994

#2073 scan only runtime dependencies for vulnerabilities
  build.gradle
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2073

#2060 NFDIV-1995 : added welsh notification for co granted
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/ConditionalOrderPronouncedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2060

#2065 NFDIV-1993: Set up POST_INFORMATION_TO_COURT Welsh notification
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/PostInformationToCourtNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2065

#2068 NFDIV-1990
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitConditionalOrderIT.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/Applicant1AppliedForConditionalOrderNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2068

#2062 NFDIV-2027
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/AppliedForConditionalOrderNotificationIT.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/Applicant1AppliedForConditionalOrderNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/Applicant2AppliedForConditionalOrderNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2062

#2040 NFDIV-2240 : Welsh divorce application summary doc
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/JurisdictionConnections.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationSoleTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProvider.java
  src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicationTemplateDataProvider.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/DivorceApplicationSoleTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/provider/ApplicantTemplateDataProviderTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/provider/ApplicationTemplateDataProviderTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2040

#2050 NFDIV-2290
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2050

#2084 NFDIV-2418
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosDisputed.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemIssueAosUnDisputed.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2084

#2045 Add NoP A1 document Welsh translation template
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerIssueApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContentIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContentIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant1NoticeOfProceeding.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedings.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingsWithAddressContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant1NoticeOfProceedingTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedingsTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2045

#2095 Include OfflineDocumentReceived as pre state for Draft AOS
  charts/nfdiv-case-api/Chart.yaml
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2095

#2097 Suppress tomcat CVEs
  config/owasp/suppressions.xml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-2097
