Repository hmcts/nfdiv-case-api, pull requests merged in 2023-10, with the labels that each got.

#3236 NFDIV-3736: Update template for final order overdue
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant1AppliedForFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant2AppliedForFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/FinalOrderRequestedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SwitchedToSoleFoNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/FinalOrderNotificationCommonContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/FinalOrderRequestedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3236

#3221 Use CCD in AAT for PRs
  Jenkinsfile_CNP
  bin/remove-case-type-from-data-store.sql
  bin/remove-case-type-from-def-store.sql
  bin/remove-case-type.sh
  charts/nfdiv-case-api/Chart.yaml
  charts/nfdiv-case-api/values.preview.template.yaml
  charts/nfdiv-case-api/values.yaml
  src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRejectedFT.java
  src/functionalTest/java/uk/gov/hmcts/divorce/citizen/CitizenResendInviteFT.java
  src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorGeneralApplicationFT.java
  src/functionalTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationFT.java
  src/functionalTest/java/uk/gov/hmcts/divorce/testutil/CaseDocumentAccessManagement.java
  src/functionalTest/java/uk/gov/hmcts/divorce/testutil/FunctionalTestSuite.java
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPronounceListIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/BulkTriggerServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/CaseRemovalServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/ScheduleCaseServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateServiceIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/testutil/PaymentWireMock.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/BulkActionCaseTypeConfig.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/endpoint/BulkScanCaseTransformationController.java
  src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/NoFaultDivorce.java
  src/main/java/uk/gov/hmcts/divorce/document/DocAssemblyService.java
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
  src/main/java/uk/gov/hmcts/divorce/payment/model/CreditAccountPaymentRequest.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemCreateBulkCaseListTask.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdCreateService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/BulkActionCaseTypeConfigTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkscan/endpoint/BulkScanCaseTransformationControllerTest.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/NoFaultDivorceTest.java
  src/test/java/uk/gov/hmcts/divorce/document/DocAssemblyServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/convert/CaseDetailsConverterTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemCreateBulkCaseListTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdCreateServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3221

#3244 Nfdiv 3745 missing notification
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1IntendToSwitchToSoleFoNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/SwitchToSoleSolicitorTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorIntendsToSwitchToSoleFoNotification.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1IntendToSwitchToSoleFoNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/SwitchToSoleSolicitorTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorIntendsToSwitchToSoleFoNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3244

#3248 add logging
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3248

#3249 fix case_type
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
  src/main/java/uk/gov/hmcts/divorce/payment/model/CreditAccountPaymentRequest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3249

#3250 Nfdiv 3738 fix boot run
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRejectedFT.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3250

#3259 NFDIV-3756: Allow citizen-applicant2-update-application when in Offli…
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateApplication.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3259

#3266 NFDIV-3614: Update docs
  src/main/resources/D10.pdf
  src/main/resources/D36.pdf
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3266

#3292 CVE-2023-5072
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3292

#3293 Fix for nfd addresses
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3293

#3305 Limit the total number of cases returned from a CCD search query
  charts/nfdiv-case-api/Chart.yaml
  charts/nfdiv-case-api/values.yaml
  src/functionalTest/resources/application.yaml
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-3305
