Repository hmcts/nfdiv-case-api, pull requests merged in 2024-10, with the labels that each got.

#4050 [NFDIV-4314] Create payment service requests in backend (Part 1)
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-case-api-pr-4050

#4045 [NFDIV-4395] Hide respondent FO tab fields until FO application is complete
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4045

#4040 NFDIV-4329 Return error from Draft AoS if AoS already submitted
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java
  src/test/java/uk/gov/hmcts/divorce/common/event/DraftAosTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4040

#4036 NFDIV-4260 Use solicitor specific templates for co granted coversheet if applicant / respondent represented
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/ConditionalOrderPronouncedDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/ConditionalOrderPronouncedCoverLetterHelper.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/ConditionalOrderPronouncedDocumentPackTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4036

#4066 NFDIV-4138: Update ccd def cleanup chart
  charts/nfdiv-case-api/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4066

#4025 [NFDIV-4314] Create payment service requests in backend (Part 2)
  src/functionalTest/java/uk/gov/hmcts/divorce/citizen/CitizenSubmitApplicationFT.java
  src/functionalTest/java/uk/gov/hmcts/divorce/testutil/FunctionalTestSuite.java
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateServiceRequestIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/common/RespondentApplyForFinalOrderIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/testutil/PaymentWireMock.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateServiceRequest.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/RespondentApplyForFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentClient.java
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
  src/main/java/uk/gov/hmcts/divorce/payment/model/CasePaymentRequest.java
  src/main/java/uk/gov/hmcts/divorce/payment/model/CreateServiceRequestBody.java
  src/main/java/uk/gov/hmcts/divorce/payment/model/ServiceReferenceResponse.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateServiceRequestTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/RespondentApplyForFinalOrderTest.java
  src/test/java/uk/gov/hmcts/divorce/payment/PaymentServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestConstants.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4025

#4029 NFDIV-4353 Hide outcome of conditional order tab for solicitors
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4029

#4064 NFDIV-4402 - Restrict deletion of documents in 'Upload document' event.
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocument.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocumentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4064

#4089 [NFDIV-4422] Add general referral type to search filters
  src/main/java/uk/gov/hmcts/divorce/divorcecase/search/CaseFieldsConstants.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/search/SearchInputFields.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4089

#4098 NFDIV-4430 - Introduce workflow to mark PRs and issues as stale or closed
  .github/workflows/stale.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4098

#4100 NFDIV-4430 Update workflow to a scheduled job for 3PM each day
  .github/workflows/stale.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4100

#4103 Nfdiv-4430 Running stale workflow scheduled at 3AM everyday
  .github/workflows/stale.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4103

#4105 [NFDIV-4410] Make CI fail when CCD definition import fails
  src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4105

#4099 NFDIV-4422 add SystemGenerateCurrentStateCountsReport runnable
  Jenkinsfile_CNP
  build.gradle
  charts/nfdiv-case-api/Chart.yaml
  charts/nfdiv-case-api/values.preview.template.yaml
  charts/nfdiv-case-api/values.yaml
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/CaseApiApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/StateReportNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/java/uk/gov/hmcts/divorce/notification/NotificationService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemGenerateCurrentStateCountsReport.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CoreCaseDataApiWithStateModifiedDate.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CoreCaseDataConfiguration.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/ReturnedCaseDetails.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/ReturnedCases.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/StateReportNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemGenerateCurrentStateCountsReportTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CoreCaseDataApiWithStateModifiedDateTest.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4099

#4109 [NFDIV-4410] Allow high level data setup to fail in demo, preview and ithc
  src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4109

#4035 NFDIV-4214 find match based on fullnames and date of marriage
  src/cftlib/java/uk/gov/hmcts/divorce/cftlib/CftLibConfig.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerFindMatches.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseMatch.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
  src/main/java/uk/gov/hmcts/divorce/notification/FormatUtil.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerFindMatchesTest.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/CaseMatchTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4035

#4115 NFDIV-4330: Add user permissions for cron testing in AAT
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenPaymentMade.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/RespondentFinalOrderPaymentMade.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4115

#4053 [NFDIV-4398] Allow citizens to resubmit CO
  src/main/java/uk/gov/hmcts/divorce/common/service/task/ResetConditionalOrderFlags.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4053

#4118 [NFDIV-4410] Use CCD Environment in high level data setup logic
  src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4118

#4124 [NFDIV-4422] Query all cases when generating state counts report
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemGenerateCurrentStateCountsReport.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchService.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemGenerateCurrentStateCountsReportTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdSearchServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4124

#4125 NFDIV-4441 Joint: Send Notification to Solicitor when other party responds
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponsePartnerNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorRespondRequestForInformation.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorRespondRequestForInformation.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponsePartnerNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/NotificationDispatcherTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorRespondRequestForInformationTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorRespondRequestForInformationTest.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4125
