Repository hmcts/nfdiv-case-api, pull requests merged in 2025-07, with the labels that each got.

#4398 [NFDIV-4775] Turn off elastic search indexing for fields we don't need to search against
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AcknowledgementOfService.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeService.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeServiceOutcome.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Bailiff.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ClarificationResponse.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderQuestions.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/DivorceGeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FeeDetails.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FinalOrderAuthorisation.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralApplication.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralEmail.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralLetter.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralReferral.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Jurisdiction.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/MarriageDetails.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformation.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationList.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationOfflineResponseDraft.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationResponse.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationResponseDraft.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/SolicitorService.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4398

#4478 [NFDIV-4737] Service application payments and state transition
  src/functionalTest/resources/application.yaml
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPayment.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenServicePaymentMade.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitServiceApplication.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/interimapplications/DeemedServiceApplicationSubmittedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/service/InterimApplicationSubmissionService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/PaymentValidatorService.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeService.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/AlternativeServiceType.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ApplicationAnswers.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/DeemedServiceJourneyOptions.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/FeeDetails.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/InterimApplicationOptions.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/InterimApplicationType.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/NoResponseJourneyOptions.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DeemedServiceApplicationTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/print/generator/DeemedServiceApplicationGenerator.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/java/uk/gov/hmcts/divorce/payment/service/PaymentSetupService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenServicePaymentMadeTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitServiceApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/interimapplications/DeemedServiceApplicationSubmittedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/InterimApplicationSubmissionServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/DeemedServiceApplicationTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/print/generator/DeemedServiceApplicationGeneratorTest.java
  src/test/java/uk/gov/hmcts/divorce/payment/service/PaymentSetupServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4478

#4564 [NFDIV-4932] Prevent overwrites to access codes
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant1Test.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2Test.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-case-api-pr-4564

#4578 NFDIV-4939 - Update docmosis reference for AoS Overdue template
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4578

#4580 NFDIV-4931: Update cron query to use correct field values
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemJsDisputedAnswerOverdueTask.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemJsDisputedAnswerOverdueTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4580

#4582 Temporarily allow pipeline pass when def import fails due to conflict
  src/main/java/uk/gov/hmcts/divorce/common/ccd/HighLevelDataSetupApp.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4582

#4587 NFDIV-4920 - Update docmosis reference for CO refusal templates
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4587

#4553 [NFDIV-4898] Turn off auto close JSON content for Jackson
  src/main/java/uk/gov/hmcts/divorce/bulkscan/validation/data/OcrDataFields.java
  src/main/java/uk/gov/hmcts/divorce/common/config/jackson/JacksonConfiguration.java
  src/main/java/uk/gov/hmcts/divorce/common/config/jackson/JacksonConfigurationVerifier.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-case-api-pr-4553

#4562 NFDIV-4907: Fix issue with sending multiple letters
  src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCase.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemProgressHeldCaseTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, rel:nfdiv-case-api-pr-4562

#4561 NFDIV-4889: Add intend to delay question to the respondent answers doc
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/RespondentAnswersTemplateContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/content/RespondentAnswersTemplateContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4561

#4593 [NFDIV-4957] Replace old coversheets and create coversheets for offline respondents
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedings.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedingsTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-case-api-pr-4593

#4608 NFDIV-4975 INC29919 - Add TTL_PROFILE to Regenerate D8 event
  src/main/java/uk/gov/hmcts/divorce/common/event/RegenerateApplicationDocument.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4608

#4514 NFDIV-4732: Add new address and email fields
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationService.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/Applicant1UpdatePartnerDetailsAndReissue.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/NoResponseJourneyOptions.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/NoResponsePartnerNewEmailOrPostalAddress.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/NoResponseProvidePartnerNewEmailOrAlternativeService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/Applicant1UpdatePartnerDetailsAndReissueTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4514
