Repository hmcts/nfdiv-case-api, pull requests merged in 2025-04, with the labels that each got.

#4317 NFDIV-4344: Return error when applicants confirm information not corr…
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitConditionalOrderIT.java
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrder.java
  src/test/java/uk/gov/hmcts/divorce/common/event/SubmitConditionalOrderTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4317

#4423 [NFDIV-4807] Revert name validation changes
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/UpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java
  src/main/resources/data/sole.json
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAmendCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/UpdateContactDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1Test.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2Test.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4423

#4420 NFDIV-4725 - Remove field injection in common package
  src/main/java/uk/gov/hmcts/divorce/common/config/WebMvcConfig.java
  src/main/java/uk/gov/hmcts/divorce/common/event/Applicant1Resubmit.java
  src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2ApplyForFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2Approve.java
  src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2RequestChanges.java
  src/main/java/uk/gov/hmcts/divorce/common/event/Applicant2SolicitorApplyForFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/CreateTestCase.java
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftConditionalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftJointConditionalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/InviteApplicant2.java
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitClarification.java
  src/main/java/uk/gov/hmcts/divorce/common/event/UpdateAos.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant1CanSwitchToSoleNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant1RemindAwaitingJointFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant2AppliedForFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant2CanSwitchToSoleNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant2RemindAwaitingJointFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/Applicant2SolicitorAppliedForFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicantSwitchToSoleAfterIntentionFONotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedOverseasNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationWithdrawnNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/AwaitingFinalOrderReminderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPendingReminderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/FinalOrderRequestedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/InviteApplicantToCaseNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/PartnerNotAppliedForFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ResendConditionalOrderPronouncedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ServiceApplicationNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationNotDisputedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SwitchedToSoleFoNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/service/ApplyForFinalOrderService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/GeneralReferralService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/HoldingPeriodService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/SubmissionService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/SubmitConfirmService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/WithdrawCaseService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/GenerateFormHelper.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SendAosNotifications.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SendRegeneratedCOPronouncedCoverLetters.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SendSubmissionNotifications.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetDateSubmitted.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetFinalOrderFieldsAsApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetFinalOrderFieldsAsApplicant2.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetFinalOrderFieldsAsApplicant2Sol.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetSubmissionAndDueDate.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetupCaseFlags.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4420

#4421 NFDIV-4729 - Remove field injection from solicitor package
  src/main/java/uk/gov/hmcts/divorce/solicitor/client/pba/PbaService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorIntendsSwitchToSoleFo.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorIntendsSwitchToSoleFo.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorSwitchToSoleFo.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorChangeServiceRequest.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorConfirmService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorCreateApplication.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorGeneralApplication.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitJointApplication.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant1ContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicant2ContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBrokenForApplicant2.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutTheSolicitor.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorAppliedForConditionalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorIntendsToSwitchToSoleFoNotification.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorSwitchToSoleCoNotification.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorCreateApplicationService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorSubmitJointApplicationService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/SolicitorUpdateApplicationService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/DivorceApplicationDraft.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetApplicant1SolicitorAddress.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/task/SetConfirmServiceDueDate.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4421

#4418 NFDIV-4663 - Welsh translations
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4418

#4415 NFDIV-4777 - Updates for change in fees impacting NFD
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SubmitAosIT.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotification.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ConditionalOrderQuestions.java
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4415

#4425 NFDIV-4652 - Add welsh template notification to applicant when sol stops rep
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4425

#4369 NFDIV-4674: Add guide links for solicitors
  src/main/java/uk/gov/hmcts/divorce/common/event/ApplyForFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/common/event/SubmitClarification.java
  src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolApplyForFinalOrderDetails.java
  src/main/java/uk/gov/hmcts/divorce/common/event/page/Applicant2SolConfirmContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoS.java
  src/main/java/uk/gov/hmcts/divorce/common/event/page/ConditionalOrderReviewAoSApplicant2.java
  src/main/java/uk/gov/hmcts/divorce/common/event/page/GeneralApplicationSelectApplicationType.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorArchiveCase.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorConfirmService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageIrretrievablyBrokenForApplicant2.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolHowDoYouWantToApplyForDivorce.java
Labels: ns:nfdiv, prd:nfdiv, stale, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4369

#4426 NFDIV-4639 - Add welsh template for Joint app solicitors
  src/main/java/uk/gov/hmcts/divorce/common/notification/FinalOrderRequestedNotification.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/notification/SolicitorAppliedForConditionalOrderNotification.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4426

#4409 [NFDIV-4642] Add Welsh templates
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/DisputedApplicationAnswerReceivedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationNotDisputedNotification.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-case-api-pr-4409

#4375 [NFDIV-4687] Citizen Withdraw Draft
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenWithdrawn.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationWithdrawnNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/service/WithdrawCaseService.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenWithdrawnTest.java
  src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationWithdrawnNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/WithdrawCaseServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4375

#4439 NFDIV-4835 - Stop sending paper app received letter for JS cases
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4439

#4433 NFDIV-4779 Pre-populate applicant addresses in solicitor update case
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplication.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorUpdateApplicationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4433

#4441 NFDIV-4804 - Update event names for linking events
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4441

#4438 [NFDIV-4801] Fix code smells related to stream.collect
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRemoveCasesFromBulkList.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/data/BulkActionCaseData.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/BulkCaseProcessingService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/BulkTriggerService.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/endpoint/BulkScanCaseTransformationController.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerExpediteFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGrantFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocument.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Jurisdiction.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentGenerator.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentUtil.java
  src/main/java/uk/gov/hmcts/divorce/document/DraftApplicationRemovalService.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderCommonContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/provider/ApplicationTemplateDataProvider.java
  src/main/java/uk/gov/hmcts/divorce/document/print/BulkPrintService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/client/pba/PbaService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/service/CcdAccessService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/convert/CaseDetailsListConverter.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/FailedBulkCaseRemover.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/bulkaction/SystemCreateBulkCaseListTask.java
  src/test/java/uk/gov/hmcts/divorce/common/service/ProcessConfidentialDocumentsServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/StateTest.java
  src/test/java/uk/gov/hmcts/divorce/document/DocumentUtilTest.java
  src/test/java/uk/gov/hmcts/divorce/legaladvisor/service/printer/LetterPrinterTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolPaymentTest.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4438

#4436 NFDIV-4796 - Update sol notification with additional details
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4436

#4431 NFDIV-4664 Add welsh templates
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/Applicant1AppliedForConditionalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/Applicant2AppliedForConditionalOrderNotification.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4431

#4432 NFDIV-4665 - Add welsh notification templates
  src/main/java/uk/gov/hmcts/divorce/notification/SwitchToSoleSolicitorTemplateContent.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-case-api-pr-4432

#4384 NFDIV-4689: Add final order granted date field to event
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRegenerateCourtOrdersIT.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerExpediteFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGrantFinalOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/FinalOrderGrantedNotification.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/FinalOrderGrantedTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/FinalOrderGrantedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/FinalOrderGrantedTemplateContentTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4384

#4456 NFDIV-4837 - Remove field injection from citizen package
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2NotBroken.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateApplication.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenIntendToSwitchToSoleFO.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenResendInvite.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSaveAndClose.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSwitchedToSole.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1ResubmitNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant1SwitchToSoleNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2ApprovedNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2NotBrokenNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2RequestChangesNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/Applicant2SwitchToSoleNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationRemindApplicant2Notification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSentForReviewNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/ApplicationSubmittedNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/BailiffServiceSuccessfulNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/BailiffServiceUnsuccessfulNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/DisputeFormOverdueOverdueNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/DisputedApplicationAnswerReceivedNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/GeneralApplicationReceivedNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationApprovedReminder.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/JointApplicationNotReviewedNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/NocSolRemovedCitizenNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/RespondentSolicitorReminderNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/SaveAndSignOutNotificationHandler.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/SwitchToSoleCoNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/ClarificationSubmittedNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/PostInformationToCourtNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/service/SwitchToSoleService.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4456

#4450 [NFDIV-4813] Add new search filters for superusers to perform fraud checks
  src/main/java/uk/gov/hmcts/divorce/divorcecase/search/CaseFieldsConstants.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/search/SearchInputFields.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4450

#4458 NFDIV-4829 - Remove code smell issues for unused assignments
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerChangeServiceRequest.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/EmailUpdateService.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/DropCaseTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/LinkBulkCaseProviderTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/ProcessFailedScheduledCasesTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/ProcessFailedToUnlinkBulkCaseTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCasesTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCourtHearingDetailsTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/task/UpdatePronouncementJudgeDetailsTaskTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8FormToCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8sFormToCaseTransformerTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateCaseFlagTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateGeneralOrderTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralApplicationReceivedTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmailTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralLetterTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAcceptedTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareForCaseFlagsTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareGeneralEmailAttachmentsTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveGeneralOrderTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveScannedDocumentTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant1EmailTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant2EmailTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/EmailUpdateServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/GeneralEmailNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedingsTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/RegenerateApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SetApplicant2EmailTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SetupCaseFlagsTest.java
  src/test/java/uk/gov/hmcts/divorce/payment/service/PaymentServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorUpdateContactDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorUpdateContactDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorGeneralApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorStopRepresentingClientTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/GeneralApplicationSelectFeeTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemPronounceCaseTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4458
