Repository hmcts/nfdiv-case-api, pull requests merged in 2025-03, with the labels that each got.

#4360 [NFDIV-4721] Add event to correct case TTL
  build.gradle
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemCorrectTtl.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4360

#4321 NFDIV-4678 Allow blanking of applicants' email
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant1Email.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant2Email.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/EmailUpdateService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant1EmailTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant2EmailTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/EmailUpdateServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4321

#4298 NFDIV-4534: Add notification for respondent started drafting aos
  src/main/java/uk/gov/hmcts/divorce/common/event/DraftAos.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/RespondentDraftAosStartedNotification.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/RespondentDraftAosStartedTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/event/DraftAosTest.java
  src/test/java/uk/gov/hmcts/divorce/common/notification/RespondentDraftAosStartedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/RespondentDraftAosStartedTemplateContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4298

#4372 NFDIV-4503 - Add welsh template to send to applicant
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4372

#4285 NFDIV-4535: Add do not attend court notification
  src/functionalTest/resources/request/casedata/ccd-callback-casedata-system-update-case-with-court-hearing.json
  src/integrationTest/java/uk/gov/hmcts/divorce/caseworker/CaseworkerRegenerateCourtOrdersIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearingIT.java
  src/integrationTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRegenerateCourtOrders.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/EntitlementGrantedConditionalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/CertificateOfEntitlementCoverLetterTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/CertificateOfEntitlementDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemUpdateCaseWithCourtHearing.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateCertificateOfEntitlementHelper.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/conditionalorder/EntitlementGrantedConditionalOrderNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/CertificateOfEntitlementDocumentPackTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateCertificateOfEntitlementHelperTest.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4285

#4363 [NFDIV-4504] Add missing Welsh notify template
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4363

#4354 NFDIV-4688 - Use generic name when first name is not present
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4354

#4364 [NFDIV-4661] Welsh template for other solicitor applied FO
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4364

#4376 NFDIV-4629 - Add welsh template to send to app solicitor
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4376

#4377 [NFDIV-4631] Add Welsh notification to inform sol they can apply for CO
  src/main/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/AwaitingConditionalOrderNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4377

#4383 NFDIV-4630 - Add welsh templates
  src/main/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/common/notification/ApplicationIssuedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4383

#4382 NFDIV-4641 - Add welsh templates
  src/main/java/uk/gov/hmcts/divorce/common/notification/ConditionalOrderPronouncedNotification.java
  src/main/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorMoreInfoDecisionNotification.java
  src/main/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorRejectedDecisionNotification.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorMoreInfoDecisionNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/legaladvisor/notification/LegalAdvisorRejectedDecisionNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4382

#4351 NFDIV-4300 - Reason field for issuing application when respondent address is absent
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Application.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/ApplicationTab.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplicationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4351

#4386 [NFDIV-4709] Use OCI java base chart
  charts/nfdiv-case-api/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4386

#4389 [NFDIV-4709] Update remaining charts to OCI
  charts/nfdiv-case-api/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4389

#4371 [NFDIV-4701] Generate D11 for respondent apply for FO doc pack
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/ApplyForFinalOrderDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateD11Form.java
  src/main/resources/D11.pdf
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/ApplyForFinalOrderDocumentPackTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/task/GenerateD11FormTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4371

#4390 [NFDIV-4727] Remove field injection from legaladvisor classes
  src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorGeneralConsideration.java
  src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeDecision.java
  src/main/java/uk/gov/hmcts/divorce/legaladvisor/event/LegalAdvisorMakeServiceDecision.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4390

#4362 NFDIV-4720: Prevent already pronounced cases from pronouncement again
  src/integrationTest/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementServiceIT.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/filter/CaseProcessingStateFilter.java
  src/test/java/uk/gov/hmcts/divorce/bulkaction/service/filter/CaseProcessingStateFilterTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-case-api-pr-4362

#4330 NFDIV-4628 Allow Grant Final order event to select uploaded docs when FO is OOT
  src/functionalTest/resources/request/casedata/ccd-callback-general-order-about-to-submit.json
  src/functionalTest/resources/request/casedata/ccd-callback-general-order.json
  src/functionalTest/resources/responses/response-caseworker-general-order-mid-event.json
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateGeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/GeneralOrderDraft.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/GeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/ScannedGeneralOrderOrGeneratedGeneralOrder.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateGeneralOrderTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrderTest.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4330

#4343 NFDIV-4675 - Regenerate accesscode only when no access code is present
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedings.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedingsTest.java
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-case-api-pr-4343

#4385 NFDIV-4703 Show events in event history for CW and super user
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemLinkApplicant2.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4385

#4406 Upgrade config gen to 5.5.19
  build.gradle
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4406

#4388 [NFDIV-4698] Remove field injection from bulkaction and bulkscan packages
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerDropCase.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerEditBulkCase.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPrintPronouncement.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerPronounceList.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRemoveCasesFromBulkList.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/CaseworkerRetryPronounceList.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/ccd/event/SuperuserRemoveCaseFromBulkList.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/BulkCaseProcessingService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/BulkTriggerService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CasePronouncementService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CaseRemovalService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/CaseTriggerService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/PronouncementListDocService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/service/ScheduleCaseService.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/DropCaseTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/ProcessFailedScheduledCasesTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/ProcessFailedToUnlinkBulkCaseTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/PronounceCasesTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/RemoveCasesTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/RetryPronounceCasesTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCasesToBeRemovedTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/UpdateCourtHearingDetailsTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/task/UpdatePronouncementJudgeDetailsTask.java
  src/main/java/uk/gov/hmcts/divorce/bulkaction/util/BulkCaseTaskUtil.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/endpoint/BulkScanCaseTransformationController.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/endpoint/ValidationController.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/ApplicationTransformer.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/BulkScanFormTransformerFactory.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/BulkScanService.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/CommonFormToCaseTransformer.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8FormToCaseTransformer.java
  src/main/java/uk/gov/hmcts/divorce/bulkscan/transformation/D8sFormToCaseTransformer.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4388

#4355 [NFDIV-4711] Adjust cancel case invite event for use by both applicants
  src/integrationTest/java/uk/gov/hmcts/divorce/systemupdate/event/SystemCancelCaseInviteIT.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemCancelCaseInvite.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemCancelCaseInviteTest.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4355

#4391 NFDIV-4724 - Remove field injection in caseworker package
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddBailiffReturn.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAddNote.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServiceApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAlternativeServicePayment.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerAnswerReceived.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerChangeServiceRequest.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmAlternativeService.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmBailiffRefusal.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmService.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateCaseFlag.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateGeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreatePaperCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralEmail.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferral.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerGeneralReferralPayment.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueAmendedApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerIssueBailiffPack.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerMakeBailiffDecision.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareForCaseFlags.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerReissueApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRejected.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocument.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveGeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRescindConditionalOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant1Email.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateApplicant2Email.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUploadDocumentsAndSubmit.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerWithdrawn.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CreateGeneralOrder.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/EmailUpdateService.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/IssueApplicationService.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/ReIssueApplicationService.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/GeneralEmailNotification.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/StateReportNotification.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant1NoticeOfProceeding.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplicant2NoticeOfProceedings.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateCoversheet.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateD10Form.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/GenerateGeneralLetter.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/RegenerateApplication.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToApplicant.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosPackToRespondent.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendApplicationIssueNotifications.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetDueDateAfterIssue.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetHoldingDueDate.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetIssueDate.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SetReIssueAndDueDate.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/util/GenerateApplicationHelper.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/StateReportNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4391

#4370 NFDIV-4671 - Add Validations to Solicitor events to disallow invalid characters in names
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/MarriageCertificateDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1Test.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant2Test.java
Labels: ns:nfdiv, prd:nfdiv, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4370

#4414 [NFDIV-4795] Allow more characters in names
  src/main/java/uk/gov/hmcts/divorce/divorcecase/validation/ValidationUtil.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/validation/CaseValidationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4414

#4325 NFDIV-4622: Add notification to solicitors for RFI response
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponseNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformationResponseTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
Labels: ns:nfdiv, prd:nfdiv, stale, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4325

#4304 NFDIV-4541 Ability to request information from offline parties (paper)
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformation.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/RequestForInformationNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponseNotification.java
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponsePartnerNotification.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformation.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationResponse.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/RequestForInformationPartnerResponseTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/RequestForInformationResponseTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/RequestForInformationTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/model/DocumentType.java
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/RequestForInformationDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/RequestForInformationPartnerResponseDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/RequestForInformationResponseDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/notification/ApplicantNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/CommonContent.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformationResponseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformationTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/RequestForInformationNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponseNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/notification/CitizenRequestForInformationResponsePartnerNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/DocmosisCommonContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/RequestForInformationPartnerResponseTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/RequestForInformationResponseTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/RequestForInformationTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/RequestForInformationDocumentPackTest.java
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/RequestForInformationPartnerResponseDocumentPackTest.java
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/RequestForInformationResponseDocumentPackTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/CommonContentTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/NotificationDispatcherTest.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestConstants.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Labels: ns:nfdiv, prd:nfdiv, stale, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4304

#4394 [NFDIV-4662] Add new Welsh templates
  src/main/java/uk/gov/hmcts/divorce/citizen/notification/RespondentSolicitorReminderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/AwaitingFinalOrderNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/RespondentApplyForFinalOrderNotification.java
  src/main/resources/application.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4394

#4410 [NFDIV-4726] Swap field injection for constructor injection in document package
  src/main/java/uk/gov/hmcts/divorce/document/DocAssemblyService.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentRemovalService.java
  src/main/java/uk/gov/hmcts/divorce/document/DraftApplicationRemovalService.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ApplicationJointTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ApplicationSoleTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/BailiffApprovedOrderContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/BailiffNotApprovedOrderContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/CertificateOfServiceContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderCommonContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderPronouncedTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForAmendmentContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ConditionalOrderRefusedForClarificationContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DocmosisTemplateProvider.java
  src/main/java/uk/gov/hmcts/divorce/document/content/DraftApplicationTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/GeneralLetterTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/GeneralOrderTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingJointJudicialSeparationContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingSolicitorContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/NoticeOfProceedingsWithAddressContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/PronouncementListTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/ServiceOrderTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/print/BulkPrintService.java
  src/main/java/uk/gov/hmcts/divorce/document/task/DivorceApplicationRemover.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4410

#4378 NFDIV-4686 INC5688232 - Ability to delete documents uploaded in response to RFI
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocument.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformation.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationList.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/RequestForInformationResponse.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveDocumentTest.java
  src/test/java/uk/gov/hmcts/divorce/testutil/TestDataHelper.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4378
