Repository hmcts/nfdiv-case-api, pull requests merged in 2025-01, with the labels that each got.

#4247 [NFDIV-4587] Blank out stale document data when new general application added
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
Labels: ns:nfdiv, prd:nfdiv, stale

#4235 NFDIV-4577 doc sort fix
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocuments.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/CaseDocumentsTest.java
Labels: ns:nfdiv, prd:nfdiv, stale, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4235

#4130 [NFDIV-4403] Add new task to create service requests for data migration
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateServiceRequest.java
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemCreateServiceRequestForPaymentTask.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/schedule/SystemCreateServiceRequestForPaymentTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-case-api-pr-4130

#4254 [NFDIV-4288] Validate address present on solicitor submit
  src/integrationTest/java/uk/gov/hmcts/divorce/solicitor/SolicitorSubmitApplicationIT.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplicationTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4254

#4188 NFDIV-4011
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/CorrectPaperCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/page/UpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenApplicant2UpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenUpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/Applicant.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/search/CaseFieldsConstants.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorViewApplicant1ContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorViewApplicant2ContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/SolAboutApplicant1.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UpdateApplicant1ContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/page/UpdateApplicant2ContactDetails.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/page/UpdateContactDetailsTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes, rel:nfdiv-case-api-pr-4188

#4174 NFDIV-4519: Send both email and letter to party after NoC
  src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java
  src/test/java/uk/gov/hmcts/divorce/notification/NotificationDispatcherTest.java
Labels: ns:nfdiv, prd:nfdiv, stale, aat/no-changes, prod/no-changes

#4270 [NFDIV-4617] Block confirm service before issue
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmService.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorConfirmService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerConfirmServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorConfirmServiceTest.java
Labels: ns:nfdiv, prd:nfdiv

#4273 [NFDIV-4455] Add event for Retain and Dispose TTL migration
  src/main/java/uk/gov/hmcts/divorce/systemupdate/event/SystemSetTimeToLive.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/event/SystemSetTimeToLiveTest.java
Labels: ns:nfdiv, prd:nfdiv

#4203 NFDIV-4465 Allow AoS to be submitted in AwaitingConditionalOrder
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SoleApplicationDisputedNotificationIT.java
  src/integrationTest/java/uk/gov/hmcts/divorce/common/SoleApplicationNotDisputedNotificationIT.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosResponseLetterPackToApplicant.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationNotDisputedNotification.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SendAosNotifications.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentConstants.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/AosResponseLetterTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/content/templatecontent/AosUndefendedResponseLetterTemplateContent.java
  src/main/java/uk/gov/hmcts/divorce/document/print/documentpack/AosResponseAwaitingConditionalOrderDocumentPack.java
  src/main/java/uk/gov/hmcts/divorce/notification/ApplicantNotification.java
  src/main/java/uk/gov/hmcts/divorce/notification/EmailTemplateName.java
  src/main/java/uk/gov/hmcts/divorce/notification/NotificationDispatcher.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/task/SendAosResponseLetterPackToApplicantTest.java
  src/test/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationDisputedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/notification/SoleApplicationNotDisputedNotificationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SendAosNotificationsTest.java
  src/test/java/uk/gov/hmcts/divorce/document/content/AosResponseLetterTemplateContentTest.java
  src/test/java/uk/gov/hmcts/divorce/document/print/documentpack/AosResponseAwaitingConditionalOrderDocumentPackTest.java
  src/test/java/uk/gov/hmcts/divorce/notification/NotificationDispatcherTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4203

#4280 NFDIV-4632 - Initialise case flags structure in case data when case is submitted
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAccepted.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/CaseFlagsService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/SubmissionService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetupCaseFlags.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/PartyFlags.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/InternalCaseFlagsAccess.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAcceptedTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseFlagsServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/SubmissionServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SetupCaseFlagsTest.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/InternalCaseFlagsAccessTest.java
Labels: ns:nfdiv, prd:nfdiv

#4261 NFDIV-4319 - Set HMCTSService ID when case is being submitted
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAccepted.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCase.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/CaseFlagsService.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenPaymentMade.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplication.java
  src/main/java/uk/gov/hmcts/divorce/common/service/SubmissionService.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetupCaseFlags.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/PartyFlags.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/access/InternalCaseFlagsAccess.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplication.java
  src/main/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAcceptedTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerProgressPaperCaseTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseFlagsServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenPaymentMadeTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenSubmitApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/SubmissionServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SetupCaseFlagsTest.java
  src/test/java/uk/gov/hmcts/divorce/divorcecase/model/access/InternalCaseFlagsAccessTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/SolicitorSubmitApplicationTest.java
  src/test/java/uk/gov/hmcts/divorce/systemupdate/service/CcdUpdateServiceTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4261

#4281 NFDIV-4343 - Implementation of Case Flags 2.1 for NFD
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateCaseFlag.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerManageCaseFlag.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChange.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareForCaseFlags.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/CaseFlagsService.java
  src/main/java/uk/gov/hmcts/divorce/citizen/service/SwitchToSoleService.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/CaseData.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/tab/CaseTypeTab.java
  src/main/java/uk/gov/hmcts/divorce/noticeofchange/event/SystemApplyNoticeOfChange.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorUpdateContactDetails.java
  src/main/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorUpdateContactDetails.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerCreateCaseFlagTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerManageCaseFlagTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerNoticeOfChangeTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPrepareForCaseFlagsTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerUpdateContactDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/CaseFlagsServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/citizen/service/SwitchToSoleServiceTest.java
  src/test/java/uk/gov/hmcts/divorce/noticeofchange/event/SystemApplyNoticeOfChangeTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/Applicant1SolicitorUpdateContactDetailsTest.java
  src/test/java/uk/gov/hmcts/divorce/solicitor/event/Applicant2SolicitorUpdateContactDetailsTest.java
Labels: ns:nfdiv, prd:nfdiv

#4163 [NFDIV-4433] Allow card payments after HWF refused
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHWFPartPaymentMade.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfApplicationAccepted.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfEvidenceRequested.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfPartPaymentRequired.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerHwfRefused.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerPaymentMade.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformation.java
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformationResponse.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenAddPayment.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateServiceRequest.java
  src/main/java/uk/gov/hmcts/divorce/citizen/event/CitizenPaymentMade.java
  src/main/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmission.java
  src/main/java/uk/gov/hmcts/divorce/divorcecase/model/State.java
  src/test/java/uk/gov/hmcts/divorce/citizen/event/CitizenCreateServiceRequestTest.java
  src/test/java/uk/gov/hmcts/divorce/common/service/task/SetStateAfterSubmissionTest.java
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/no-changes, prod/no-changes

#4297 [NFDIV-4646] Remove deprecated F&P keyword
  src/main/java/uk/gov/hmcts/divorce/caseworker/service/notification/FinalOrderGrantedNotification.java
  src/main/java/uk/gov/hmcts/divorce/payment/PaymentService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/service/notification/FinalOrderGrantedNotificationTest.java
Labels: ns:nfdiv, prd:nfdiv

#4296 NFDIV-4620 Block RFI from being available in "Draft", "AwaitingPayment"
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRequestForInformation.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-case-api-pr-4296

#4295 [NFDIV-4596] Add event to remove general letters
  src/main/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveGeneralLetter.java
  src/main/java/uk/gov/hmcts/divorce/document/DocumentRemovalService.java
  src/test/java/uk/gov/hmcts/divorce/caseworker/event/CaseworkerRemoveGeneralLetterTest.java
Labels: ns:nfdiv, prd:nfdiv
